// <auto-generated />
using System;
using FacilityMonitoring.Common.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FacilityMonitoring.Common.Migrations
{
    [DbContext(typeof(FacilityContext))]
    partial class FacilityContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FacilityMonitoring.Common.Model.ModbusDevice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DisplayName");

                    b.Property<string>("Identifier");

                    b.Property<string>("IpAddress");

                    b.Property<int>("Port");

                    b.Property<int>("SlaveAddress");

                    b.Property<string>("Status");

                    b.HasKey("Id");

                    b.ToTable("ModbusDevices");
                });

            modelBuilder.Entity("FacilityMonitoring.Common.Model.Reading", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.Property<string>("Identifier");

                    b.Property<int>("ModbusDeviceId");

                    b.Property<DateTime>("TimeStamp");

                    b.HasKey("Id");

                    b.HasIndex("ModbusDeviceId");

                    b.ToTable("Readings");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Reading");
                });

            modelBuilder.Entity("FacilityMonitoring.Common.Model.AmmoniaBoxReading", b =>
                {
                    b.HasBaseType("FacilityMonitoring.Common.Model.Reading");

                    b.Property<string>("ActiveTank");

                    b.Property<int>("Heater1DutyCycle");

                    b.Property<int>("Heater2DutyCycle");

                    b.Property<int>("Heater3DutyCycle");

                    b.Property<int>("Heater4DutyCycle");

                    b.Property<string>("Scale1Status");

                    b.Property<string>("Scale2Status");

                    b.Property<string>("Scale3Status");

                    b.Property<string>("Scale4Status");

                    b.Property<bool>("Tank1Alarm");

                    b.Property<int>("Tank1Tare");

                    b.Property<double>("Tank1Temperature");

                    b.Property<bool>("Tank1Warning");

                    b.Property<int>("Tank1Weight");

                    b.Property<bool>("Tank2Alarm");

                    b.Property<int>("Tank2Tare");

                    b.Property<double>("Tank2Temperature");

                    b.Property<bool>("Tank2Warning");

                    b.Property<int>("Tank2Weight");

                    b.Property<bool>("Tank3Alarm");

                    b.Property<int>("Tank3Tare");

                    b.Property<double>("Tank3Temperature");

                    b.Property<bool>("Tank3Warning");

                    b.Property<int>("Tank3Weight");

                    b.Property<bool>("Tank4Alarm");

                    b.Property<int>("Tank4Tare");

                    b.Property<double>("Tank4Temperature");

                    b.Property<bool>("Tank4Warning");

                    b.Property<int>("Tank4Weight");

                    b.HasDiscriminator().HasValue("AmmoniaBoxReading");
                });

            modelBuilder.Entity("FacilityMonitoring.Common.Model.H2GenReading", b =>
                {
                    b.HasBaseType("FacilityMonitoring.Common.Model.Reading");

                    b.Property<bool>("A200_Drain_Valve");

                    b.Property<bool>("A200_Inlet_Valve");

                    b.Property<bool>("A200_Level_Empty");

                    b.Property<bool>("A200_Level_Flooded");

                    b.Property<bool>("A200_Level_High");

                    b.Property<bool>("A200_Level_Low");

                    b.Property<bool>("A300_Drain_Valve");

                    b.Property<bool>("A300_Level_Empty");

                    b.Property<bool>("A300_Level_Flooded");

                    b.Property<bool>("A300_Level_High");

                    b.Property<bool>("A300_Level_Low");

                    b.Property<string>("All_System_Errors");

                    b.Property<string>("All_System_Warnings");

                    b.Property<double>("Ambient_Temperature");

                    b.Property<double>("CG220_level");

                    b.Property<double>("DI_water_quality");

                    b.Property<bool>("Dryer_Valve1");

                    b.Property<bool>("Dryer_Valve2");

                    b.Property<bool>("Dryer_Valve3");

                    b.Property<bool>("Dryer_Valve4");

                    b.Property<double>("Ext_Water_Quality");

                    b.Property<double>("Heat_Exchanger_Water_Temp");

                    b.Property<double>("Heat_sink_Temperature");

                    b.Property<double>("Hydrogen_flow");

                    b.Property<int>("Operation_Mode");

                    b.Property<int>("PSV_A1");

                    b.Property<int>("PSV_A1_A2");

                    b.Property<int>("PSV_A3");

                    b.Property<int>("PSV_B1");

                    b.Property<int>("PSV_B2");

                    b.Property<int>("PSV_B3");

                    b.Property<int>("PSV_C1");

                    b.Property<int>("PSV_C2");

                    b.Property<int>("PSV_C3");

                    b.Property<int>("PS_Fault_A1");

                    b.Property<int>("PS_Fault_A2");

                    b.Property<int>("PS_Fault_A3");

                    b.Property<int>("PS_Fault_B1");

                    b.Property<int>("PS_Fault_B2");

                    b.Property<int>("PS_Fault_B3");

                    b.Property<int>("PS_Fault_C1");

                    b.Property<int>("PS_Fault_C2");

                    b.Property<int>("PS_Fault_C3");

                    b.Property<double>("Product_pressure");

                    b.Property<int>("Ps_card_enable_A1");

                    b.Property<int>("Ps_card_enable_A2");

                    b.Property<int>("Ps_card_enable_A3");

                    b.Property<int>("Ps_card_enable_B1");

                    b.Property<int>("Ps_card_enable_B2");

                    b.Property<int>("Ps_card_enable_B3");

                    b.Property<int>("Ps_card_enable_C1");

                    b.Property<int>("Ps_card_enable_C2");

                    b.Property<int>("Ps_card_enable_C3");

                    b.Property<bool>("Pump_control");

                    b.Property<bool>("Stack_A_Water_Flow");

                    b.Property<int>("Stack_A_monitor_Current");

                    b.Property<bool>("Stack_A_valve");

                    b.Property<bool>("Stack_B_Water_Flow");

                    b.Property<int>("Stack_B_monitor_Current");

                    b.Property<bool>("Stack_B_valve");

                    b.Property<bool>("Stack_C_Water_Flow");

                    b.Property<int>("Stack_C_monitor_Current");

                    b.Property<bool>("Stack_C_valve");

                    b.Property<double>("System_24V_power");

                    b.Property<double>("System_3V_power");

                    b.Property<double>("System_5V_power");

                    b.Property<double>("System_Pressure");

                    b.Property<int>("System_State");

                    b.Property<int>("System_mode");

                    b.Property<double>("Thermal_Control_Valve");

                    b.Property<bool>("Vent_Valve");

                    b.Property<double>("Water_Quality");

                    b.Property<double>("Water_Temperature");

                    b.Property<int>("ps_unit_status");

                    b.HasDiscriminator().HasValue("H2GenReading");
                });

            modelBuilder.Entity("FacilityMonitoring.Common.Model.Reading", b =>
                {
                    b.HasOne("FacilityMonitoring.Common.Model.ModbusDevice", "ModbusDevice")
                        .WithMany("Readings")
                        .HasForeignKey("ModbusDeviceId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
