// <auto-generated />
using System;
using FacilityMonitoring.Common.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FacilityMonitoring.Common.Migrations
{
    [DbContext(typeof(FacilityContext))]
    partial class FacilityContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FacilityMonitoring.Common.Data.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Category");
                });

            modelBuilder.Entity("FacilityMonitoring.Common.Data.Entities.GeneratorSystemError", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("A200_EMPTY_ERR")
                        .HasColumnType("int");

                    b.Property<int>("A200_FLOODED_ERR")
                        .HasColumnType("int");

                    b.Property<int>("CAL_DUE_CG220")
                        .HasColumnType("int");

                    b.Property<int>("CHECKSUM_ERROR_CONTROLLER")
                        .HasColumnType("int");

                    b.Property<int>("EMPTY_A300")
                        .HasColumnType("int");

                    b.Property<int>("FAULT_DIGITAL_FUSES")
                        .HasColumnType("int");

                    b.Property<int>("FLOODED_A300")
                        .HasColumnType("int");

                    b.Property<int>("H2GenReadingId")
                        .HasColumnType("int");

                    b.Property<int>("HIGH_CONCENTRATION_CG220")
                        .HasColumnType("int");

                    b.Property<int>("HIGH_TEMP_TE159_PS_ENCLOSURE")
                        .HasColumnType("int");

                    b.Property<int>("INVALID_STATE_A200_SWITCH")
                        .HasColumnType("int");

                    b.Property<int>("INVALID_STATE_FSW250_FLOW_SWITCHES")
                        .HasColumnType("int");

                    b.Property<int>("INVALID_STATE_S300_SWITCH")
                        .HasColumnType("int");

                    b.Property<int>("LOW_TEMP_TE159_PS_ENCLOSURE")
                        .HasColumnType("int");

                    b.Property<int>("LOW_WATER_FLOW_STACK_A")
                        .HasColumnType("int");

                    b.Property<int>("LOW_WATER_FLOW_STACK_B")
                        .HasColumnType("int");

                    b.Property<int>("LOW_WATER_FLOW_STACK_C")
                        .HasColumnType("int");

                    b.Property<int>("NO_STACKS_PRESENT")
                        .HasColumnType("int");

                    b.Property<int>("OUT_OF_RANGE_24V_5V_3V_SUPPLY")
                        .HasColumnType("int");

                    b.Property<int>("OUT_OF_RANGE_CG220")
                        .HasColumnType("int");

                    b.Property<int>("OUT_OF_RANGE_PT307_SYS_PRESSURE")
                        .HasColumnType("int");

                    b.Property<int>("OUT_OF_RANGE_TE218_SYS_TEMP")
                        .HasColumnType("int");

                    b.Property<int>("PRESS_TIMEOUT_ERR")
                        .HasColumnType("int");

                    b.Property<int>("PREVIOUS_ERROR_RESET")
                        .HasColumnType("int");

                    b.Property<int>("PRE_START_TIMEOUT_A200")
                        .HasColumnType("int");

                    b.Property<int>("PSU_COMM_ERROR")
                        .HasColumnType("int");

                    b.Property<int>("PSU_ERROR")
                        .HasColumnType("int");

                    b.Property<int>("PS_CARD_A1_FAULT")
                        .HasColumnType("int");

                    b.Property<int>("PS_CARD_A1_V_HIGH")
                        .HasColumnType("int");

                    b.Property<int>("PS_CARD_A1_V_LOW")
                        .HasColumnType("int");

                    b.Property<int>("PS_CARD_A2_FAULT")
                        .HasColumnType("int");

                    b.Property<int>("PS_CARD_A2_V_HIGH")
                        .HasColumnType("int");

                    b.Property<int>("PS_CARD_A2_V_LOW")
                        .HasColumnType("int");

                    b.Property<int>("PS_CARD_A3_FAULT")
                        .HasColumnType("int");

                    b.Property<int>("PS_CARD_A3_V_HIGH")
                        .HasColumnType("int");

                    b.Property<int>("PS_CARD_A3_V_LOW")
                        .HasColumnType("int");

                    b.Property<int>("PS_CARD_B1_FAULT")
                        .HasColumnType("int");

                    b.Property<int>("PS_CARD_B1_V_HIGH")
                        .HasColumnType("int");

                    b.Property<int>("PS_CARD_B1_V_LOW")
                        .HasColumnType("int");

                    b.Property<int>("PS_CARD_B2_FAULT")
                        .HasColumnType("int");

                    b.Property<int>("PS_CARD_B2_V_HIGH")
                        .HasColumnType("int");

                    b.Property<int>("PS_CARD_B2_V_LOW")
                        .HasColumnType("int");

                    b.Property<int>("PS_CARD_B3_FAULT")
                        .HasColumnType("int");

                    b.Property<int>("PS_CARD_B3_V_HIGH")
                        .HasColumnType("int");

                    b.Property<int>("PS_CARD_B3_V_LOW")
                        .HasColumnType("int");

                    b.Property<int>("PS_CARD_C1_FAULT")
                        .HasColumnType("int");

                    b.Property<int>("PS_CARD_C1_V_HIGH")
                        .HasColumnType("int");

                    b.Property<int>("PS_CARD_C1_V_LOW")
                        .HasColumnType("int");

                    b.Property<int>("PS_CARD_C2_FAULT")
                        .HasColumnType("int");

                    b.Property<int>("PS_CARD_C2_V_HIGH")
                        .HasColumnType("int");

                    b.Property<int>("PS_CARD_C2_V_LOW")
                        .HasColumnType("int");

                    b.Property<int>("PS_CARD_C3_FAULT")
                        .HasColumnType("int");

                    b.Property<int>("PS_CARD_C3_V_HIGH")
                        .HasColumnType("int");

                    b.Property<int>("PS_CARD_C3_V_LOW")
                        .HasColumnType("int");

                    b.Property<int>("RESERVED_E08")
                        .HasColumnType("int");

                    b.Property<int>("RESERVED_E16_B")
                        .HasColumnType("int");

                    b.Property<int>("RESERVED_E20_B")
                        .HasColumnType("int");

                    b.Property<int>("RESERVED_E21")
                        .HasColumnType("int");

                    b.Property<int>("RESERVED_E22")
                        .HasColumnType("int");

                    b.Property<int>("RESERVED_E23")
                        .HasColumnType("int");

                    b.Property<int>("RESERVED_E25")
                        .HasColumnType("int");

                    b.Property<int>("RESERVED_E27")
                        .HasColumnType("int");

                    b.Property<int>("RESERVED_E32")
                        .HasColumnType("int");

                    b.Property<int>("RESERVED_E35")
                        .HasColumnType("int");

                    b.Property<int>("RESERVED_E39")
                        .HasColumnType("int");

                    b.Property<int>("RESERVED_E43")
                        .HasColumnType("int");

                    b.Property<int>("RESERVED_E44")
                        .HasColumnType("int");

                    b.Property<int>("RESERVED_E45")
                        .HasColumnType("int");

                    b.Property<int>("RESERVED_E48")
                        .HasColumnType("int");

                    b.Property<int>("RS209_OUT_OF_RANGE")
                        .HasColumnType("int");

                    b.Property<int>("RS209_SYS_WATER_QUALITY")
                        .HasColumnType("int");

                    b.Property<int>("STACK_A_CUR_HIGH")
                        .HasColumnType("int");

                    b.Property<int>("STACK_A_CUR_LOW")
                        .HasColumnType("int");

                    b.Property<int>("STACK_B_CUR_HIGH")
                        .HasColumnType("int");

                    b.Property<int>("STACK_B_CUR_LOW")
                        .HasColumnType("int");

                    b.Property<int>("STACK_C_CUR_HIGH")
                        .HasColumnType("int");

                    b.Property<int>("STACK_C_CUR_LOW")
                        .HasColumnType("int");

                    b.Property<int>("SYSTEM_TEMP_SHUTDOWN_ERR")
                        .HasColumnType("int");

                    b.Property<int>("SYS_PRESSURE_HIGH_ERR")
                        .HasColumnType("int");

                    b.Property<int>("SYS_PRESSURE_LOW_ERR")
                        .HasColumnType("int");

                    b.Property<int>("WATER_FROZEN_ERR")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("H2GenReadingId")
                        .IsUnique();

                    b.ToTable("GeneratorSystemErrors");
                });

            modelBuilder.Entity("FacilityMonitoring.Common.Data.Entities.GeneratorSystemWarning", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("A200_LOW_FLOW_WARNING")
                        .HasColumnType("int");

                    b.Property<int>("BAD_GURAD_WARN")
                        .HasColumnType("int");

                    b.Property<int>("CABINET_TEMP_HIGH")
                        .HasColumnType("int");

                    b.Property<int>("CAL_GAS_PRESSURE_LOW")
                        .HasColumnType("int");

                    b.Property<int>("CG120_LEVEL_HIGH")
                        .HasColumnType("int");

                    b.Property<int>("CG120_LOW")
                        .HasColumnType("int");

                    b.Property<int>("CG220_LEVEL_HIGH")
                        .HasColumnType("int");

                    b.Property<int>("CG_CAL_CANCEL_WARN")
                        .HasColumnType("int");

                    b.Property<int>("CG_CAL_DUE_WARN")
                        .HasColumnType("int");

                    b.Property<int>("CG_LEVEL_LOW")
                        .HasColumnType("int");

                    b.Property<int>("COOL_FLOW_LOW_WARN")
                        .HasColumnType("int");

                    b.Property<int>("COOL_TEMP_HIGH_WARN")
                        .HasColumnType("int");

                    b.Property<int>("COOL_TEMP_LOW_WARN")
                        .HasColumnType("int");

                    b.Property<int>("DI_WQ_SENSOR_FAIL_WARN")
                        .HasColumnType("int");

                    b.Property<int>("DI_WQ_WARN")
                        .HasColumnType("int");

                    b.Property<int>("H2GenReadingId")
                        .HasColumnType("int");

                    b.Property<int>("HEAT_SINK_TEMP_HIGH")
                        .HasColumnType("int");

                    b.Property<int>("PRODUCT_PRESS_HIGH_WARN")
                        .HasColumnType("int");

                    b.Property<int>("PURGE_PRESSURE_WARN")
                        .HasColumnType("int");

                    b.Property<int>("STACK_WATER_FLOW_WARN")
                        .HasColumnType("int");

                    b.Property<int>("SYSTEM_PRESSURE_LOW")
                        .HasColumnType("int");

                    b.Property<int>("SYSTEM_TEMP_WARN")
                        .HasColumnType("int");

                    b.Property<int>("WATER_QUAL_WARN")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("H2GenReadingId")
                        .IsUnique();

                    b.ToTable("GeneratorSystemWarnings");
                });

            modelBuilder.Entity("FacilityMonitoring.Common.Data.Entities.H2GenReading", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("A200DrainValve")
                        .HasColumnType("int");

                    b.Property<int>("A200InletValve")
                        .HasColumnType("int");

                    b.Property<int>("A200LevelEmpty")
                        .HasColumnType("int");

                    b.Property<int>("A200LevelFlooded")
                        .HasColumnType("int");

                    b.Property<int>("A200LevelHigh")
                        .HasColumnType("int");

                    b.Property<int>("A200LevelLow")
                        .HasColumnType("int");

                    b.Property<int>("A300DrainValve")
                        .HasColumnType("int");

                    b.Property<int>("A300LevelEmpty")
                        .HasColumnType("int");

                    b.Property<int>("A300LevelFlooded")
                        .HasColumnType("int");

                    b.Property<int>("A300LevelHigh")
                        .HasColumnType("int");

                    b.Property<int>("A300LevelLow")
                        .HasColumnType("int");

                    b.Property<double>("AmbientTemperature")
                        .HasColumnType("float");

                    b.Property<double>("CG220Level")
                        .HasColumnType("float");

                    b.Property<double>("DIWaterQuality")
                        .HasColumnType("float");

                    b.Property<int>("DryerValve1")
                        .HasColumnType("int");

                    b.Property<int>("DryerValve2")
                        .HasColumnType("int");

                    b.Property<int>("DryerValve3")
                        .HasColumnType("int");

                    b.Property<int>("DryerValve4")
                        .HasColumnType("int");

                    b.Property<double>("ExtWaterQuality")
                        .HasColumnType("float");

                    b.Property<int>("GeneratorId")
                        .HasColumnType("int");

                    b.Property<double>("HeatExchangerWaterTemp")
                        .HasColumnType("float");

                    b.Property<double>("HeatSinkTemperature")
                        .HasColumnType("float");

                    b.Property<double>("HydrogenFlow")
                        .HasColumnType("float");

                    b.Property<string>("Identifier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OperationMode")
                        .HasColumnType("int");

                    b.Property<int>("PSFaultA1")
                        .HasColumnType("int");

                    b.Property<int>("PSFaultA2")
                        .HasColumnType("int");

                    b.Property<int>("PSFaultB1")
                        .HasColumnType("int");

                    b.Property<int>("PSFaultB2")
                        .HasColumnType("int");

                    b.Property<int>("PSFaultC1")
                        .HasColumnType("int");

                    b.Property<int>("PSFaultC2")
                        .HasColumnType("int");

                    b.Property<int>("PSFault_A3")
                        .HasColumnType("int");

                    b.Property<int>("PSFault_B3")
                        .HasColumnType("int");

                    b.Property<int>("PSFault_C3")
                        .HasColumnType("int");

                    b.Property<int>("PSUnitStatus")
                        .HasColumnType("int");

                    b.Property<int>("PSV_A1")
                        .HasColumnType("int");

                    b.Property<int>("PSV_A2")
                        .HasColumnType("int");

                    b.Property<int>("PSV_A3")
                        .HasColumnType("int");

                    b.Property<int>("PSV_B1")
                        .HasColumnType("int");

                    b.Property<int>("PSV_B2")
                        .HasColumnType("int");

                    b.Property<int>("PSV_B3")
                        .HasColumnType("int");

                    b.Property<int>("PSV_C1")
                        .HasColumnType("int");

                    b.Property<int>("PSV_C2")
                        .HasColumnType("int");

                    b.Property<int>("PSV_C3")
                        .HasColumnType("int");

                    b.Property<double>("ProductPressure")
                        .HasColumnType("float");

                    b.Property<int>("PsCardEnableA1")
                        .HasColumnType("int");

                    b.Property<int>("PsCardEnableA2")
                        .HasColumnType("int");

                    b.Property<int>("PsCardEnableB1")
                        .HasColumnType("int");

                    b.Property<int>("PsCardEnableB2")
                        .HasColumnType("int");

                    b.Property<int>("PsCardEnableC1")
                        .HasColumnType("int");

                    b.Property<int>("PsCardEnableC2")
                        .HasColumnType("int");

                    b.Property<int>("PsCardEnable_A3")
                        .HasColumnType("int");

                    b.Property<int>("PsCardEnable_B3")
                        .HasColumnType("int");

                    b.Property<int>("PsCardEnable_C3")
                        .HasColumnType("int");

                    b.Property<int>("PumpControl")
                        .HasColumnType("int");

                    b.Property<int>("StackAMonitorCurrent")
                        .HasColumnType("int");

                    b.Property<int>("StackAValve")
                        .HasColumnType("int");

                    b.Property<int>("StackAWaterFlow")
                        .HasColumnType("int");

                    b.Property<int>("StackBMonitorCurrent")
                        .HasColumnType("int");

                    b.Property<int>("StackBValve")
                        .HasColumnType("int");

                    b.Property<int>("StackBWaterFlow")
                        .HasColumnType("int");

                    b.Property<int>("StackCMonitorCurrent")
                        .HasColumnType("int");

                    b.Property<int>("StackCValve")
                        .HasColumnType("int");

                    b.Property<int>("StackCWaterFlow")
                        .HasColumnType("int");

                    b.Property<double>("System24VPower")
                        .HasColumnType("float");

                    b.Property<double>("System3VPower")
                        .HasColumnType("float");

                    b.Property<double>("System5VPower")
                        .HasColumnType("float");

                    b.Property<int>("SystemMode")
                        .HasColumnType("int");

                    b.Property<double>("SystemPressure")
                        .HasColumnType("float");

                    b.Property<int>("SystemState")
                        .HasColumnType("int");

                    b.Property<double>("ThermalControlValve")
                        .HasColumnType("float");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("datetime2");

                    b.Property<int>("VentValve")
                        .HasColumnType("int");

                    b.Property<double>("WaterQuality")
                        .HasColumnType("float");

                    b.Property<double>("WaterTemperature")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("GeneratorId");

                    b.ToTable("H2GenReadings");
                });

            modelBuilder.Entity("FacilityMonitoring.Common.Data.Entities.ModbusDevice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("BypassAll")
                        .HasColumnType("bit");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Identifier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IpAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Port")
                        .HasColumnType("int");

                    b.Property<double>("ReadInterval")
                        .HasColumnType("float");

                    b.Property<double>("SaveInterval")
                        .HasColumnType("float");

                    b.Property<int>("SlaveAddress")
                        .HasColumnType("int");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ModbusDevices");

                    b.HasDiscriminator<string>("Discriminator").HasValue("ModbusDevice");
                });

            modelBuilder.Entity("FacilityMonitoring.Common.Data.Entities.MonitorBoxAlert", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AnalogCh1")
                        .HasColumnType("int");

                    b.Property<int>("AnalogCh10")
                        .HasColumnType("int");

                    b.Property<int>("AnalogCh11")
                        .HasColumnType("int");

                    b.Property<int>("AnalogCh12")
                        .HasColumnType("int");

                    b.Property<int>("AnalogCh13")
                        .HasColumnType("int");

                    b.Property<int>("AnalogCh14")
                        .HasColumnType("int");

                    b.Property<int>("AnalogCh15")
                        .HasColumnType("int");

                    b.Property<int>("AnalogCh16")
                        .HasColumnType("int");

                    b.Property<int>("AnalogCh2")
                        .HasColumnType("int");

                    b.Property<int>("AnalogCh3")
                        .HasColumnType("int");

                    b.Property<int>("AnalogCh4")
                        .HasColumnType("int");

                    b.Property<int>("AnalogCh5")
                        .HasColumnType("int");

                    b.Property<int>("AnalogCh6")
                        .HasColumnType("int");

                    b.Property<int>("AnalogCh7")
                        .HasColumnType("int");

                    b.Property<int>("AnalogCh8")
                        .HasColumnType("int");

                    b.Property<int>("AnalogCh9")
                        .HasColumnType("int");

                    b.Property<bool>("DigitalCh1")
                        .HasColumnType("bit");

                    b.Property<bool>("DigitalCh10")
                        .HasColumnType("bit");

                    b.Property<bool>("DigitalCh11")
                        .HasColumnType("bit");

                    b.Property<bool>("DigitalCh12")
                        .HasColumnType("bit");

                    b.Property<bool>("DigitalCh13")
                        .HasColumnType("bit");

                    b.Property<bool>("DigitalCh14")
                        .HasColumnType("bit");

                    b.Property<bool>("DigitalCh15")
                        .HasColumnType("bit");

                    b.Property<bool>("DigitalCh16")
                        .HasColumnType("bit");

                    b.Property<bool>("DigitalCh17")
                        .HasColumnType("bit");

                    b.Property<bool>("DigitalCh18")
                        .HasColumnType("bit");

                    b.Property<bool>("DigitalCh19")
                        .HasColumnType("bit");

                    b.Property<bool>("DigitalCh2")
                        .HasColumnType("bit");

                    b.Property<bool>("DigitalCh20")
                        .HasColumnType("bit");

                    b.Property<bool>("DigitalCh21")
                        .HasColumnType("bit");

                    b.Property<bool>("DigitalCh22")
                        .HasColumnType("bit");

                    b.Property<bool>("DigitalCh23")
                        .HasColumnType("bit");

                    b.Property<bool>("DigitalCh24")
                        .HasColumnType("bit");

                    b.Property<bool>("DigitalCh25")
                        .HasColumnType("bit");

                    b.Property<bool>("DigitalCh26")
                        .HasColumnType("bit");

                    b.Property<bool>("DigitalCh27")
                        .HasColumnType("bit");

                    b.Property<bool>("DigitalCh28")
                        .HasColumnType("bit");

                    b.Property<bool>("DigitalCh29")
                        .HasColumnType("bit");

                    b.Property<bool>("DigitalCh3")
                        .HasColumnType("bit");

                    b.Property<bool>("DigitalCh30")
                        .HasColumnType("bit");

                    b.Property<bool>("DigitalCh31")
                        .HasColumnType("bit");

                    b.Property<bool>("DigitalCh32")
                        .HasColumnType("bit");

                    b.Property<bool>("DigitalCh33")
                        .HasColumnType("bit");

                    b.Property<bool>("DigitalCh34")
                        .HasColumnType("bit");

                    b.Property<bool>("DigitalCh35")
                        .HasColumnType("bit");

                    b.Property<bool>("DigitalCh36")
                        .HasColumnType("bit");

                    b.Property<bool>("DigitalCh37")
                        .HasColumnType("bit");

                    b.Property<bool>("DigitalCh38")
                        .HasColumnType("bit");

                    b.Property<bool>("DigitalCh4")
                        .HasColumnType("bit");

                    b.Property<bool>("DigitalCh5")
                        .HasColumnType("bit");

                    b.Property<bool>("DigitalCh6")
                        .HasColumnType("bit");

                    b.Property<bool>("DigitalCh7")
                        .HasColumnType("bit");

                    b.Property<bool>("DigitalCh8")
                        .HasColumnType("bit");

                    b.Property<bool>("DigitalCh9")
                        .HasColumnType("bit");

                    b.Property<int>("MonitorBoxReadingId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MonitorBoxReadingId")
                        .IsUnique();

                    b.ToTable("MonitorBoxAlerts");
                });

            modelBuilder.Entity("FacilityMonitoring.Common.Data.Entities.MonitorBoxReading", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Alarm1")
                        .HasColumnType("bit");

                    b.Property<bool>("Alarm2")
                        .HasColumnType("bit");

                    b.Property<bool>("Alarm3")
                        .HasColumnType("bit");

                    b.Property<double>("AnalogCh1")
                        .HasColumnType("float");

                    b.Property<double>("AnalogCh10")
                        .HasColumnType("float");

                    b.Property<double>("AnalogCh11")
                        .HasColumnType("float");

                    b.Property<double>("AnalogCh12")
                        .HasColumnType("float");

                    b.Property<double>("AnalogCh13")
                        .HasColumnType("float");

                    b.Property<double>("AnalogCh14")
                        .HasColumnType("float");

                    b.Property<double>("AnalogCh15")
                        .HasColumnType("float");

                    b.Property<double>("AnalogCh16")
                        .HasColumnType("float");

                    b.Property<double>("AnalogCh2")
                        .HasColumnType("float");

                    b.Property<double>("AnalogCh3")
                        .HasColumnType("float");

                    b.Property<double>("AnalogCh4")
                        .HasColumnType("float");

                    b.Property<double>("AnalogCh5")
                        .HasColumnType("float");

                    b.Property<double>("AnalogCh6")
                        .HasColumnType("float");

                    b.Property<double>("AnalogCh7")
                        .HasColumnType("float");

                    b.Property<double>("AnalogCh8")
                        .HasColumnType("float");

                    b.Property<double>("AnalogCh9")
                        .HasColumnType("float");

                    b.Property<bool>("DigitalCh1")
                        .HasColumnType("bit");

                    b.Property<bool>("DigitalCh10")
                        .HasColumnType("bit");

                    b.Property<bool>("DigitalCh11")
                        .HasColumnType("bit");

                    b.Property<bool>("DigitalCh12")
                        .HasColumnType("bit");

                    b.Property<bool>("DigitalCh13")
                        .HasColumnType("bit");

                    b.Property<bool>("DigitalCh14")
                        .HasColumnType("bit");

                    b.Property<bool>("DigitalCh15")
                        .HasColumnType("bit");

                    b.Property<bool>("DigitalCh16")
                        .HasColumnType("bit");

                    b.Property<bool>("DigitalCh17")
                        .HasColumnType("bit");

                    b.Property<bool>("DigitalCh18")
                        .HasColumnType("bit");

                    b.Property<bool>("DigitalCh19")
                        .HasColumnType("bit");

                    b.Property<bool>("DigitalCh2")
                        .HasColumnType("bit");

                    b.Property<bool>("DigitalCh20")
                        .HasColumnType("bit");

                    b.Property<bool>("DigitalCh21")
                        .HasColumnType("bit");

                    b.Property<bool>("DigitalCh22")
                        .HasColumnType("bit");

                    b.Property<bool>("DigitalCh23")
                        .HasColumnType("bit");

                    b.Property<bool>("DigitalCh24")
                        .HasColumnType("bit");

                    b.Property<bool>("DigitalCh25")
                        .HasColumnType("bit");

                    b.Property<bool>("DigitalCh26")
                        .HasColumnType("bit");

                    b.Property<bool>("DigitalCh27")
                        .HasColumnType("bit");

                    b.Property<bool>("DigitalCh28")
                        .HasColumnType("bit");

                    b.Property<bool>("DigitalCh29")
                        .HasColumnType("bit");

                    b.Property<bool>("DigitalCh3")
                        .HasColumnType("bit");

                    b.Property<bool>("DigitalCh30")
                        .HasColumnType("bit");

                    b.Property<bool>("DigitalCh31")
                        .HasColumnType("bit");

                    b.Property<bool>("DigitalCh32")
                        .HasColumnType("bit");

                    b.Property<bool>("DigitalCh33")
                        .HasColumnType("bit");

                    b.Property<bool>("DigitalCh34")
                        .HasColumnType("bit");

                    b.Property<bool>("DigitalCh35")
                        .HasColumnType("bit");

                    b.Property<bool>("DigitalCh36")
                        .HasColumnType("bit");

                    b.Property<bool>("DigitalCh37")
                        .HasColumnType("bit");

                    b.Property<bool>("DigitalCh38")
                        .HasColumnType("bit");

                    b.Property<bool>("DigitalCh4")
                        .HasColumnType("bit");

                    b.Property<bool>("DigitalCh5")
                        .HasColumnType("bit");

                    b.Property<bool>("DigitalCh6")
                        .HasColumnType("bit");

                    b.Property<bool>("DigitalCh7")
                        .HasColumnType("bit");

                    b.Property<bool>("DigitalCh8")
                        .HasColumnType("bit");

                    b.Property<bool>("DigitalCh9")
                        .HasColumnType("bit");

                    b.Property<int>("GenericMonitorBoxId")
                        .HasColumnType("int");

                    b.Property<string>("Identifier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("OutputCh1")
                        .HasColumnType("bit");

                    b.Property<bool>("OutputCh10")
                        .HasColumnType("bit");

                    b.Property<bool>("OutputCh2")
                        .HasColumnType("bit");

                    b.Property<bool>("OutputCh3")
                        .HasColumnType("bit");

                    b.Property<bool>("OutputCh4")
                        .HasColumnType("bit");

                    b.Property<bool>("OutputCh5")
                        .HasColumnType("bit");

                    b.Property<bool>("OutputCh6")
                        .HasColumnType("bit");

                    b.Property<bool>("OutputCh7")
                        .HasColumnType("bit");

                    b.Property<bool>("OutputCh8")
                        .HasColumnType("bit");

                    b.Property<bool>("OutputCh9")
                        .HasColumnType("bit");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("GenericMonitorBoxId");

                    b.ToTable("MonitorBoxReadings");
                });

            modelBuilder.Entity("FacilityMonitoring.Common.Data.Entities.Register", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Bypass")
                        .HasColumnType("bit");

                    b.Property<bool>("Connected")
                        .HasColumnType("bit");

                    b.Property<int>("DeviceId")
                        .HasColumnType("int");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Display")
                        .HasColumnType("bit");

                    b.Property<int>("Logic")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PropertyMap")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RegisterIndex")
                        .HasColumnType("int");

                    b.Property<int>("RegisterLength")
                        .HasColumnType("int");

                    b.Property<int?>("SensorTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.HasIndex("SensorTypeId");

                    b.ToTable("Registers");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Register");
                });

            modelBuilder.Entity("FacilityMonitoring.Common.Data.Entities.TankScaleAlert", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AmmoniaControllerReadingId")
                        .HasColumnType("int");

                    b.Property<int>("Tank1Alert")
                        .HasColumnType("int");

                    b.Property<int>("Tank2Alert")
                        .HasColumnType("int");

                    b.Property<int>("Tank3Alert")
                        .HasColumnType("int");

                    b.Property<int>("Tank4Alert")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AmmoniaControllerReadingId")
                        .IsUnique();

                    b.ToTable("TankScaleAlerts");
                });

            modelBuilder.Entity("FacilityMonitoring.Common.Data.Entities.TankScaleReading", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AmmoniaControllerId")
                        .HasColumnType("int");

                    b.Property<int>("Heater1DutyCycle")
                        .HasColumnType("int");

                    b.Property<int>("Heater2DutyCycle")
                        .HasColumnType("int");

                    b.Property<int>("Heater3DutyCycle")
                        .HasColumnType("int");

                    b.Property<int>("Heater4DutyCycle")
                        .HasColumnType("int");

                    b.Property<bool>("Tank1Alarm")
                        .HasColumnType("bit");

                    b.Property<int>("Tank1Gas")
                        .HasColumnType("int");

                    b.Property<int>("Tank1NonZero")
                        .HasColumnType("int");

                    b.Property<int>("Tank1NonZeroCal")
                        .HasColumnType("int");

                    b.Property<int>("Tank1Tare")
                        .HasColumnType("int");

                    b.Property<double>("Tank1Temperature")
                        .HasColumnType("float");

                    b.Property<int>("Tank1Total")
                        .HasColumnType("int");

                    b.Property<bool>("Tank1Warning")
                        .HasColumnType("bit");

                    b.Property<int>("Tank1Weight")
                        .HasColumnType("int");

                    b.Property<int>("Tank1Zero")
                        .HasColumnType("int");

                    b.Property<int>("Tank1ZeroCal")
                        .HasColumnType("int");

                    b.Property<bool>("Tank2Alarm")
                        .HasColumnType("bit");

                    b.Property<int>("Tank2Gas")
                        .HasColumnType("int");

                    b.Property<int>("Tank2NonZero")
                        .HasColumnType("int");

                    b.Property<int>("Tank2NonZeroCal")
                        .HasColumnType("int");

                    b.Property<int>("Tank2Tare")
                        .HasColumnType("int");

                    b.Property<double>("Tank2Temperature")
                        .HasColumnType("float");

                    b.Property<int>("Tank2Total")
                        .HasColumnType("int");

                    b.Property<bool>("Tank2Warning")
                        .HasColumnType("bit");

                    b.Property<int>("Tank2Weight")
                        .HasColumnType("int");

                    b.Property<int>("Tank2Zero")
                        .HasColumnType("int");

                    b.Property<int>("Tank2ZeroCal")
                        .HasColumnType("int");

                    b.Property<bool>("Tank3Alarm")
                        .HasColumnType("bit");

                    b.Property<int>("Tank3Gas")
                        .HasColumnType("int");

                    b.Property<int>("Tank3NonZero")
                        .HasColumnType("int");

                    b.Property<int>("Tank3NonZeroCal")
                        .HasColumnType("int");

                    b.Property<int>("Tank3Tare")
                        .HasColumnType("int");

                    b.Property<double>("Tank3Temperature")
                        .HasColumnType("float");

                    b.Property<int>("Tank3Total")
                        .HasColumnType("int");

                    b.Property<bool>("Tank3Warning")
                        .HasColumnType("bit");

                    b.Property<int>("Tank3Weight")
                        .HasColumnType("int");

                    b.Property<int>("Tank3Zero")
                        .HasColumnType("int");

                    b.Property<int>("Tank3ZeroCal")
                        .HasColumnType("int");

                    b.Property<bool>("Tank4Alarm")
                        .HasColumnType("bit");

                    b.Property<int>("Tank4Gas")
                        .HasColumnType("int");

                    b.Property<int>("Tank4NonZero")
                        .HasColumnType("int");

                    b.Property<int>("Tank4NonZeroCal")
                        .HasColumnType("int");

                    b.Property<int>("Tank4Tare")
                        .HasColumnType("int");

                    b.Property<double>("Tank4Temperature")
                        .HasColumnType("float");

                    b.Property<int>("Tank4Total")
                        .HasColumnType("int");

                    b.Property<bool>("Tank4Warning")
                        .HasColumnType("bit");

                    b.Property<int>("Tank4Weight")
                        .HasColumnType("int");

                    b.Property<int>("Tank4Zero")
                        .HasColumnType("int");

                    b.Property<int>("Tank4ZeroCal")
                        .HasColumnType("int");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AmmoniaControllerId");

                    b.ToTable("TankScaleReadings");
                });

            modelBuilder.Entity("FacilityMonitoring.Common.Data.Entities.SensorType", b =>
                {
                    b.HasBaseType("FacilityMonitoring.Common.Data.Entities.Category");

                    b.Property<double>("MaxPoint")
                        .HasColumnType("float");

                    b.Property<string>("Units")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ZeroPoint")
                        .HasColumnType("float");

                    b.HasDiscriminator().HasValue("SensorType");
                });

            modelBuilder.Entity("FacilityMonitoring.Common.Data.Entities.H2Generator", b =>
                {
                    b.HasBaseType("FacilityMonitoring.Common.Data.Entities.ModbusDevice");

                    b.Property<int>("OperationMode")
                        .HasColumnType("int");

                    b.Property<int>("SystemState")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("H2Generator");
                });

            modelBuilder.Entity("FacilityMonitoring.Common.Data.Entities.MonitorBox", b =>
                {
                    b.HasBaseType("FacilityMonitoring.Common.Data.Entities.ModbusDevice");

                    b.Property<int>("AlarmAddr")
                        .HasColumnType("int");

                    b.Property<int>("AnalogChannelCount")
                        .HasColumnType("int");

                    b.Property<int>("DigitalInputChannelCount")
                        .HasColumnType("int");

                    b.Property<int>("DigitalOutputChannelCount")
                        .HasColumnType("int");

                    b.Property<int>("ModbusComAddr")
                        .HasColumnType("int");

                    b.Property<int>("SoftwareMaintAddr")
                        .HasColumnType("int");

                    b.Property<int>("StateAddr")
                        .HasColumnType("int");

                    b.Property<int>("WarningAddr")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("MonitorBox");
                });

            modelBuilder.Entity("FacilityMonitoring.Common.Data.Entities.TankScale", b =>
                {
                    b.HasBaseType("FacilityMonitoring.Common.Data.Entities.ModbusDevice");

                    b.Property<int>("ActiveTank")
                        .HasColumnType("int");

                    b.Property<int>("AlarmSetPoint")
                        .HasColumnType("int");

                    b.Property<int>("CalInputBaseAddr")
                        .HasColumnType("int");

                    b.Property<int>("CalInputLength")
                        .HasColumnType("int");

                    b.Property<int>("CalModeAddr")
                        .HasColumnType("int");

                    b.Property<int>("CoilBaseAddress")
                        .HasColumnType("int");

                    b.Property<int>("DataForInputAddr")
                        .HasColumnType("int");

                    b.Property<int>("ReadCoilLength")
                        .HasColumnType("int");

                    b.Property<int>("ReadRegisterLength")
                        .HasColumnType("int");

                    b.Property<int>("RegisterBaseAddress")
                        .HasColumnType("int");

                    b.Property<bool>("Tank1AlertEnabled")
                        .HasColumnType("bit");

                    b.Property<bool>("Tank2AlertEnabled")
                        .HasColumnType("bit");

                    b.Property<bool>("Tank3AlertEnabled")
                        .HasColumnType("bit");

                    b.Property<bool>("Tank4AlertEnabled")
                        .HasColumnType("bit");

                    b.Property<int>("WarningSetPoint")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("TankScale");
                });

            modelBuilder.Entity("FacilityMonitoring.Common.Data.Entities.AnalogChannel", b =>
                {
                    b.HasBaseType("FacilityMonitoring.Common.Data.Entities.Register");

                    b.Property<int>("Alarm1Action")
                        .HasColumnType("int");

                    b.Property<bool>("Alarm1Enabled")
                        .HasColumnType("bit");

                    b.Property<double>("Alarm1SetPoint")
                        .HasColumnType("float");

                    b.Property<int>("Alarm2Action")
                        .HasColumnType("int");

                    b.Property<bool>("Alarm2Enabled")
                        .HasColumnType("bit");

                    b.Property<double>("Alarm2SetPoint")
                        .HasColumnType("float");

                    b.Property<int>("Alarm3Action")
                        .HasColumnType("int");

                    b.Property<bool>("Alarm3Enabled")
                        .HasColumnType("bit");

                    b.Property<double>("Alarm3SetPoint")
                        .HasColumnType("float");

                    b.Property<double>("MaxValue")
                        .HasColumnType("float");

                    b.Property<double>("Offset")
                        .HasColumnType("float");

                    b.Property<double>("Resistance")
                        .HasColumnType("float");

                    b.Property<double>("Slope")
                        .HasColumnType("float");

                    b.Property<double>("ValueDivisor")
                        .HasColumnType("float");

                    b.Property<double>("ZeroValue")
                        .HasColumnType("float");

                    b.HasDiscriminator().HasValue("AnalogChannel");
                });

            modelBuilder.Entity("FacilityMonitoring.Common.Data.Entities.DigitalInputChannel", b =>
                {
                    b.HasBaseType("FacilityMonitoring.Common.Data.Entities.Register");

                    b.Property<int>("AlarmAction")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("DigitalInputChannel");
                });

            modelBuilder.Entity("FacilityMonitoring.Common.Data.Entities.DigitalOutputChannel", b =>
                {
                    b.HasBaseType("FacilityMonitoring.Common.Data.Entities.Register");

                    b.Property<int>("OutputControl")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("DigitalOutputChannel");
                });

            modelBuilder.Entity("FacilityMonitoring.Common.Data.Entities.GeneratorRegister", b =>
                {
                    b.HasBaseType("FacilityMonitoring.Common.Data.Entities.Register");

                    b.Property<int>("DataType")
                        .HasColumnType("int");

                    b.Property<int>("FunctionCode")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("GeneratorRegister");
                });

            modelBuilder.Entity("FacilityMonitoring.Common.Data.Entities.GeneratorSystemError", b =>
                {
                    b.HasOne("FacilityMonitoring.Common.Data.Entities.H2GenReading", "H2GenReading")
                        .WithOne("AllSystemErrors")
                        .HasForeignKey("FacilityMonitoring.Common.Data.Entities.GeneratorSystemError", "H2GenReadingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FacilityMonitoring.Common.Data.Entities.GeneratorSystemWarning", b =>
                {
                    b.HasOne("FacilityMonitoring.Common.Data.Entities.H2GenReading", "H2GenReading")
                        .WithOne("AllSystemWarnings")
                        .HasForeignKey("FacilityMonitoring.Common.Data.Entities.GeneratorSystemWarning", "H2GenReadingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FacilityMonitoring.Common.Data.Entities.H2GenReading", b =>
                {
                    b.HasOne("FacilityMonitoring.Common.Data.Entities.H2Generator", "H2Generator")
                        .WithMany("H2Readings")
                        .HasForeignKey("GeneratorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FacilityMonitoring.Common.Data.Entities.MonitorBoxAlert", b =>
                {
                    b.HasOne("FacilityMonitoring.Common.Data.Entities.MonitorBoxReading", "MonitorBoxReading")
                        .WithOne("MonitorBoxAlert")
                        .HasForeignKey("FacilityMonitoring.Common.Data.Entities.MonitorBoxAlert", "MonitorBoxReadingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FacilityMonitoring.Common.Data.Entities.MonitorBoxReading", b =>
                {
                    b.HasOne("FacilityMonitoring.Common.Data.Entities.MonitorBox", "GenericMonitorBox")
                        .WithMany("BoxReadings")
                        .HasForeignKey("GenericMonitorBoxId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FacilityMonitoring.Common.Data.Entities.Register", b =>
                {
                    b.HasOne("FacilityMonitoring.Common.Data.Entities.ModbusDevice", "Device")
                        .WithMany("Registers")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FacilityMonitoring.Common.Data.Entities.SensorType", "SensorType")
                        .WithMany("Registers")
                        .HasForeignKey("SensorTypeId");
                });

            modelBuilder.Entity("FacilityMonitoring.Common.Data.Entities.TankScaleAlert", b =>
                {
                    b.HasOne("FacilityMonitoring.Common.Data.Entities.TankScaleReading", "AmmoniaControllerReading")
                        .WithOne("AmmoniaControllerAlert")
                        .HasForeignKey("FacilityMonitoring.Common.Data.Entities.TankScaleAlert", "AmmoniaControllerReadingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FacilityMonitoring.Common.Data.Entities.TankScaleReading", b =>
                {
                    b.HasOne("FacilityMonitoring.Common.Data.Entities.TankScale", "AmmoniaController")
                        .WithMany("Readings")
                        .HasForeignKey("AmmoniaControllerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
